### PR TITLE
Traditional Chinese for Taiwan

### PR DESCRIPTION
**Pull request by YamiOdymel**

### CODE REVIEW

**Comment by philsturgeon** [comment]
Can you add links to the README and stuff? Thank you :D

**Comment by YamiOdymel** [comment]
Ummm, like this?

**Comment by philsturgeon** [comment]
Perfect!

**Comment by YamiOdymel** [comment]
You have no idea how awesome the license is.

**Comment by avenirer** [comment]
I guess he does...

**Comment by philsturgeon** [comment]
I think it's daft as fuck but people like it :D

**Pull request merged**
